#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# usage: vimmodified 1
# to open all files modified from '1' commit ago as buffers in vim
function vimmodified() {
  git diff --name-only HEAD HEAD~$1 | xargs -o vim -p
}
